### PR TITLE
Remove editing task and DAG metadata guide

### PR DESCRIPTION
**Pull request by kentdanas**
This legacy guide does not exemplify Airflow best practices, as it encourages editing the metadata db directly. Users should instead look to our guide on the metadata database. https://www.astronomer.io/guides/airflow-database

### CODE REVIEW

**Comment by kentdanas** [comment]
@allenbrady-astro could you put a redirect in place back to the main guides site for this one?

**Comment by allenbrady-astro** [comment]
Hey @kentdanas redirect should be live now! 🙌

**Comment by allenbrady-astro** [comment]
Oh wait I misunderstood let me fix that 😅

**Comment by kentdanas** [comment]
Thank you!! (sorry, my initial comment was a bit unclear)

**Pull request merged**
